#!/usr/bin/env bash
# while loop to print "Best school except for  (9th iteration)
count=0
while [ $count -lt 10 ]
do
if [ $count -eq 9 ]
then
echo "Hi"
echo "Best School"
else
echo "Best School"
fi
((count++))
done
